name: Manual 
on: 
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        default: Hello
        description: A cheerful world 
        required: true
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, ${{ inputs.greeting }}!"